spring:
  main:
    web-application-type: none
logging:
  pattern:
    console: '%clr(%4p): %msg%n'

cloud:
  aws:
    region: ru-central1
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${BUCKET}
    endpoint: storage.yandexcloud.net